
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Salih
 */
public class myJFrame extends javax.swing.JFrame {

    /**
     * Creates new form myJFrame
     */
    public myJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hafta", "Takım 1", "Takım 2", "Skor"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Listele");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Takım Bilgilerini Göster");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(7);
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setText("Dosya Seç");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    List<Mac> myList = new ArrayList<>();
    List<Hafta> haftalar = new ArrayList<>();
    File file;

    public void dosyaSec() {
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "*.txt", "txt");
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("turnuva.txt Dosyasını Seçiniz");

        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            listele();
        } else {
            System.out.println("Dosya Seçilmedi");
            return;
        }
    }

    public void listele() {
        String line;
        Mac takim1, takim2;
        Berabere berabere;
        Kaybedilen kaybedilen;
        Kazanma kazanma;

        Hafta hafta;
        boolean x = true;
        boolean y = true;

        try {
            FileReader fileReader = new FileReader(file);
            BufferedReader br = new BufferedReader(fileReader);
            while ((line = br.readLine()) != null) {
                String[] arrOfLine = line.split(" ");

                hafta = new Hafta();
                hafta.isim = arrOfLine[0];
                hafta.takim1 = arrOfLine[1];
                hafta.takim2 = arrOfLine[2];
                hafta.skor1 = arrOfLine[3];
                hafta.skor2 = arrOfLine[3];

                haftalar.add(hafta);

                takim1 = new Mac();
                takim2 = new Mac();
                takim1.isim = arrOfLine[1];
                takim2.isim = arrOfLine[2];

                for (Mac list : myList) {
                    if (list.isim.equals(arrOfLine[1])) {
                        takim1 = list;
                        x = false;
                    }
                    if (list.isim.equals(arrOfLine[2])) {
                        takim2 = list;
                        y = false;
                    }
                }

                int skor1 = Integer.parseInt(arrOfLine[3]);
                int skor2 = Integer.parseInt(arrOfLine[4]);
                if (skor1 == skor2) {
                    berabere = new Berabere(skor1, skor2);
                    takim1.berabere.add(berabere);
                    takim2.berabere.add(berabere);
                    takim1.puan += 1;
                    takim2.puan += 1;
                    takim1.beraberlikSayisi += 1;
                    takim2.beraberlikSayisi += 1;
                    takim1.macSayisi += 1;
                    takim2.macSayisi += 1;
                    takim1.aGol += skor1;
                    takim2.aGol += skor2;
                    takim1.yGol += skor2;
                    takim2.yGol += skor1;

                } else if (skor1 > skor2) {
                    kazanma = new Kazanma(skor1, skor2);
                    kaybedilen = new Kaybedilen(skor1, skor2);
                    takim1.kazanma.add(kazanma);
                    takim2.kaybedilen.add(kaybedilen);
                    takim1.puan += 3;
                    takim1.galibiyetSayisi += 1;
                    takim2.maglubiyetSayisi += 1;
                    takim1.macSayisi += 1;
                    takim2.macSayisi += 1;
                    takim1.aGol += skor1;
                    takim2.aGol += skor2;
                    takim1.yGol += skor2;
                    takim2.yGol += skor1;
                } else {
                    kaybedilen = new Kaybedilen(skor1, skor2);
                    kazanma = new Kazanma(skor1, skor2);
                    takim1.kaybedilen.add(kaybedilen);
                    takim2.kazanma.add(kazanma);
                    takim2.puan += 3;
                    takim1.maglubiyetSayisi += 1;
                    takim2.galibiyetSayisi += 1;
                    takim1.macSayisi += 1;
                    takim2.macSayisi += 1;
                    takim1.aGol += skor1;
                    takim2.aGol += skor2;
                    takim1.yGol += skor2;
                    takim2.yGol += skor1;
                }
                if (x) {
                    myList.add(takim1);
                }
                if (y) {
                    myList.add(takim2);
                }

                x = true;
                y = true;
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(myJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(myJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Mac myMac : myList) {
            jComboBox2.addItem(myMac.isim);
        }
        boolean kontrol = true;
        for (Hafta haftam : haftalar) {
            for (int i = 0; i < jComboBox1.getItemCount(); i++) {
                String item = jComboBox1.getItemAt(i);
                if (haftam.isim.equals(item)) {
                    kontrol = false;
                    break;
                }
            }
            if (kontrol) {
                jComboBox1.addItem(haftam.isim);
            }
            kontrol = true;
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //File file = new File("C:\\Users\\Salih\\Desktop\\turnuva.txt");
        dosyaSec();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[4];
        model.setRowCount(0);
        for (Hafta hafta : haftalar) {
            if (hafta.isim.equals(jComboBox1.getSelectedItem().toString())) {
                rowData[0] = hafta.isim;
                rowData[1] = hafta.takim1;
                rowData[2] = hafta.takim2;
                rowData[3] = hafta.skor1 + " - " + hafta.skor2;
                model.addRow(rowData);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Mac macim = getTakimInfo(myList);

        jTextArea1.setText(macim.isim + "\n"
                + "Maç Sayısı : " + macim.macSayisi + "\n"
                + "Galibiyet Sayısı : " + macim.galibiyetSayisi + "\n"
                + "Beraberlik Sayısı : " + macim.beraberlikSayisi + "\n"
                + "Mağlubiyet Sayısı : " + macim.maglubiyetSayisi + "\n"
                + "Atılan Gol Sayısı : " + macim.aGol + "\n"
                + "Yenilen Gol Sayısı : " + macim.yGol + "\n"
                + "Puan Durumu : " + macim.puan + "\n"
        );

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dosyaSec();
    }//GEN-LAST:event_jButton3ActionPerformed
    public Mac getTakimInfo(List<Mac> m) {
        for (Mac macim : myList) {
            if (macim.isim.equals(jComboBox2.getSelectedItem().toString())) {
                return macim;
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
